server:
  port: 8081
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/order_service_db
    username: postgres
    password: postgres
  jackson:
    serialization:
      indent-output: true
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  api-docs:
    enabled: true